//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности ку.
    /// </summary>
    // *** Start programmer edit section *** (ДолжностиКу CustomAttributes)

    // *** End programmer edit section *** (ДолжностиКу CustomAttributes)
    [AutoAltered()]
    [Caption("Должности ку")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиКуE", new string[] {
            "ИмяДол as \'Имя дол\'"})]
    [View("ДолжностиКуL", new string[] {
            "ИмяДол as \'Имя дол\'"})]
    public class ДолжностиКу : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмяДол;
        
        // *** Start programmer edit section *** (ДолжностиКу CustomMembers)

        // *** End programmer edit section *** (ДолжностиКу CustomMembers)

        
        /// <summary>
        /// ИмяДол.
        /// </summary>
        // *** Start programmer edit section *** (ДолжностиКу.ИмяДол CustomAttributes)

        // *** End programmer edit section *** (ДолжностиКу.ИмяДол CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяДол
        {
            get
            {
                // *** Start programmer edit section *** (ДолжностиКу.ИмяДол Get start)

                // *** End programmer edit section *** (ДолжностиКу.ИмяДол Get start)
                string result = this.fИмяДол;
                // *** Start programmer edit section *** (ДолжностиКу.ИмяДол Get end)

                // *** End programmer edit section *** (ДолжностиКу.ИмяДол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжностиКу.ИмяДол Set start)

                // *** End programmer edit section *** (ДолжностиКу.ИмяДол Set start)
                this.fИмяДол = value;
                // *** Start programmer edit section *** (ДолжностиКу.ИмяДол Set end)

                // *** End programmer edit section *** (ДолжностиКу.ИмяДол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиКуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиКуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиКуE", typeof(IIS.22.ДолжностиКу));
                }
            }
            
            /// <summary>
            /// "ДолжностиКуL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиКуL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиКуL", typeof(IIS.22.ДолжностиКу));
                }
            }
        }
    }
}
