//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет.
    /// </summary>
    // *** Start programmer edit section *** (Расчет CustomAttributes)

    // *** End programmer edit section *** (Расчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетE", new string[] {
            "Код as \'Код\'",
            "Тип as \'Тип\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Имя as \'Имя\'",
            "Сотрудники.ДолжностиКу.ИмяДол as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.Имя"})]
    [MasterViewDefineAttribute("РасчетE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("РасчетL", new string[] {
            "Код as \'Код\'",
            "Тип as \'Тип\'",
            "Сотрудники.Имя as \'Имя\'",
            "Сотрудники.ДолжностиКу.ИмяДол as \'Должность\'"})]
    public class Расчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private IIS.22.Тип fТип;
        
        private IIS.22.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Расчет CustomMembers)

        // *** End programmer edit section *** (Расчет CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Код CustomAttributes)

        // *** End programmer edit section *** (Расчет.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Код Get start)

                // *** End programmer edit section *** (Расчет.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Расчет.Код Get end)

                // *** End programmer edit section *** (Расчет.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Код Set start)

                // *** End programmer edit section *** (Расчет.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Расчет.Код Set end)

                // *** End programmer edit section *** (Расчет.Код Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Тип CustomAttributes)

        // *** End programmer edit section *** (Расчет.Тип CustomAttributes)
        public virtual IIS.22.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Тип Get start)

                // *** End programmer edit section *** (Расчет.Тип Get start)
                IIS.22.Тип result = this.fТип;
                // *** Start programmer edit section *** (Расчет.Тип Get end)

                // *** End programmer edit section *** (Расчет.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Тип Set start)

                // *** End programmer edit section *** (Расчет.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Расчет.Тип Set end)

                // *** End programmer edit section *** (Расчет.Тип Set end)
            }
        }
        
        /// <summary>
        /// Расчет.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Расчет.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.22.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Сотрудники Get start)

                // *** End programmer edit section *** (Расчет.Сотрудники Get start)
                IIS.22.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Расчет.Сотрудники Get end)

                // *** End programmer edit section *** (Расчет.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Сотрудники Set start)

                // *** End programmer edit section *** (Расчет.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Расчет.Сотрудники Set end)

                // *** End programmer edit section *** (Расчет.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетE", typeof(IIS.22.Расчет));
                }
            }
            
            /// <summary>
            /// "РасчетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетL", typeof(IIS.22.Расчет));
                }
            }
        }
    }
}
