//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "Имя as \'Имя\'",
            "ДолжностиКу as \'Должности ку\'",
            "ДолжностиКу.ИмяДол as \'Должность\'"}, Hidden=new string[] {
            "ДолжностиКу.ИмяДол"})]
    [MasterViewDefineAttribute("СотрудникиE", "ДолжностиКу", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИмяДол")]
    [View("СотрудникиL", new string[] {
            "Имя as \'Имя\'",
            "ДолжностиКу.ИмяДол as \'Должность\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private IIS.22.ДолжностиКу fДолжностиКу;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Get start)

                // *** End programmer edit section *** (Сотрудники.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Сотрудники.Имя Get end)

                // *** End programmer edit section *** (Сотрудники.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Set start)

                // *** End programmer edit section *** (Сотрудники.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Сотрудники.Имя Set end)

                // *** End programmer edit section *** (Сотрудники.Имя Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ДолжностиКу CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ДолжностиКу CustomAttributes)
        [PropertyStorage(new string[] {
                "ДолжностиКу"})]
        [NotNull()]
        public virtual IIS.22.ДолжностиКу ДолжностиКу
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ДолжностиКу Get start)

                // *** End programmer edit section *** (Сотрудники.ДолжностиКу Get start)
                IIS.22.ДолжностиКу result = this.fДолжностиКу;
                // *** Start programmer edit section *** (Сотрудники.ДолжностиКу Get end)

                // *** End programmer edit section *** (Сотрудники.ДолжностиКу Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ДолжностиКу Set start)

                // *** End programmer edit section *** (Сотрудники.ДолжностиКу Set start)
                this.fДолжностиКу = value;
                // *** Start programmer edit section *** (Сотрудники.ДолжностиКу Set end)

                // *** End programmer edit section *** (Сотрудники.ДолжностиКу Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.22.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.22.Сотрудники));
                }
            }
        }
    }
}
